# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ActionsTest < Formula
  desc ""
  homepage "https://github.com/brucemacd/test-actions"
  version "0.0.10"
  license "MIT"
  depends_on :macos

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/BruceMacD/test-actions/releases/download/0.0.10/test-actions_0.0.10_darwin_arm64.tar.gz"
      sha256 "1cc5e7f50a8a3efd8dec7f85b5523ac902fdee9b535ea01d11dba389e0bc8fe5"

      def install
        bin.install "actionsTest"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/BruceMacD/test-actions/releases/download/0.0.10/test-actions_0.0.10_darwin_amd64.tar.gz"
      sha256 "bf9f12e07a6f719a22c9cfccd008c0ac05548a072a973248d2aadc0dad8cf3f1"

      def install
        bin.install "actionsTest"
      end
    end
  end
end
