# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ActionsTest < Formula
  desc ""
  homepage "https://github.com/brucemacd/test-actions"
  version "0.0.18"
  license "MIT"
  depends_on :macos

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/BruceMacD/test-actions/releases/download/0.0.18/test-actions_0.0.18_darwin_arm64.tar.gz"
      sha256 "5dfb5d078c05bb25b1789d55bde471cbe446e00cc7ac6239f2b6c23ae3f4e94a"

      def install
        bin.install "actionsTest"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/BruceMacD/test-actions/releases/download/0.0.18/test-actions_0.0.18_darwin_amd64.tar.gz"
      sha256 "95af1228cc77b2e7836d198a1fb483b9a2fb6fbfd3475f60de5fb856ddd5f01a"

      def install
        bin.install "actionsTest"
      end
    end
  end
end
